# Generated by Django 4.1 on 2022-08-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='cumnpleanios',
            new_name='cumpleanios',
        ),
    ]
